security:
    encoders:
        Symfony\Component\Security\Core\User\User: 'auto'

    providers:
        in_memory:
            memory:
                users:
                    login: { password: '$argon2id$v=19$m=65536,t=4,p=1$WW447R9fs4pFxYBjNfByKg$5g06Q5hPoHJKdK/KeTdi1aJXe90X0ZMKUowtPduUzrg', roles: [ROLE_ADMIN] }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy
            http_basic: true

    access_control:
         - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
