parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        App\RequestHandler\RequestHandlerInterface:
            tags: ['request_handler']

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\RequestHandler\RequestHandlerLocator:
        arguments:
            $handlers: !tagged request_handler