parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        App\CommandBus\CommandHandlerInterface:
            tags: ['command_handler']

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\CommandBus\CommandBus:
        arguments:
            $handlers: !tagged command_handler